version: '3.8'
services:
  api-gateway:
    image: standardnotes/api-gateway
    env_file: docker/api-gateway.env
    environment:
      PORT: 3000
    entrypoint: ["./wait-for.sh", "syncing-server", "3000", "./wait-for.sh", "syncing-server-js", "3000", "./docker/entrypoint.sh", "start-web"]
    ports:
      - 3000:${EXPOSED_PORT}
    networks:
      syncing_server: {}

  auth:
    image: standardnotes/auth
    entrypoint: ["./wait-for.sh", "syncing-server-js", "3000", "./docker/entrypoint.sh", "start-worker"]
    env_file: docker/auth.env
    networks:
      syncing_server: {}

  syncing-server-js:
    image: standardnotes/syncing-server-js
    entrypoint: ["./wait-for.sh", "syncing-server", "3000", "./docker/entrypoint.sh", "start-web"]
    env_file: docker/syncing-server-js.env
    networks:
      syncing_server: {}

  syncing-server-js-worker:
    image: standardnotes/syncing-server-js
    entrypoint: ["./wait-for.sh", "syncing-server-js", "3000", "./docker/entrypoint.sh", "start-worker"]
    env_file: docker/syncing-server-js.env
    networks:
      syncing_server: {}

  syncing-server:
    build: .
    entrypoint: ["./wait-for.sh", "db", "3306", "./wait-for.sh", "cache", "6379", "./docker/entrypoint.sh", "start-local"]
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
      REDIS_URL: redis://cache:6379
    networks:
      standardnotes_proxy:
        aliases:
          - syncing_server
      syncing_server: {}
    volumes:
      - .:/syncing-server

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - syncing_server

  cache:
    image: redis:6.0-alpine
    volumes:
      - ./cache:/data
    ports:
      - 6379
    networks:
      - syncing_server

networks:
  syncing_server:
    name: syncing_server
  standardnotes_proxy:
    name: standardnotes
